M48
; DRILL file {KiCad 8.0.5} date 2024-10-15T13:11:50-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-15T13:11:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X6.4961Y-3.622
T2
X5.9843Y-3.8976
X6.4843Y-3.8976
T3
X5.3543Y-3.8012
X5.3543Y-3.9012
M30
